"""Add key-specific fields to Item model

Revision ID: 3483ed993305
Revises: 1d9e2f3a4b5c
Create Date: 2025-10-19 17:11:56.283290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3483ed993305'
down_revision = '1d9e2f3a4b5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('unit_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_number', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
